name: flutter_advanced_networkimage
description: An advanced image provider provides caching and retrying for
  flutter app. Now with zoomable widget and transition to image widget.
version: 0.8.0
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  http: ^0.13.3
  path: ^1.8.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0-nullsafety.17

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"
